// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeLocalZip(arg1) {
  return window['go']['main']['App']['AnalyzeLocalZip'](arg1);
}

export function BuildSourcePackage() {
  return window['go']['main']['App']['BuildSourcePackage']();
}

export function CheckRuntime() {
  return window['go']['main']['App']['CheckRuntime']();
}

export function DownloadAndAnalyzeGithub(arg1) {
  return window['go']['main']['App']['DownloadAndAnalyzeGithub'](arg1);
}

export function OpenFirmwareZip() {
  return window['go']['main']['App']['OpenFirmwareZip']();
}

export function PreviewFlashCommand(arg1) {
  return window['go']['main']['App']['PreviewFlashCommand'](arg1);
}

export function ScanDevices() {
  return window['go']['main']['App']['ScanDevices']();
}

export function StartFlash(arg1) {
  return window['go']['main']['App']['StartFlash'](arg1);
}
