// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {runtimekit} from '../models';
import {preflight} from '../models';
import {device} from '../models';

export function AnalyzeLocalZip(arg1:string):Promise<main.AnalyzeResponse>;

export function BuildSourcePackage():Promise<main.AnalyzeResponse>;

export function CheckRuntime():Promise<runtimekit.Status>;

export function DetectCompatibility(arg1:main.CompatibilityRequest):Promise<preflight.Report>;

export function DownloadAndAnalyzeGithub(arg1:main.GitHubRequest):Promise<main.AnalyzeResponse>;

export function GetLogFilePath():Promise<string>;

export function GetLogHistory():Promise<Array<string>>;

export function OpenFirmwareZip():Promise<string>;

export function PreviewFlashCommand(arg1:main.FlashRequest):Promise<string>;

export function ScanDevices():Promise<Array<device.Device>>;

export function StartFlash(arg1:main.FlashRequest):Promise<void>;
